// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqkbmpyanyeetyjdjxhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlxa2JtcHlhbnllZXR5amRqeGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDQ4OTYsImV4cCI6MjA2ODkyMDg5Nn0.6GOLlfvfqRs0u-mBOnV7hRvywuHnH7gI4qaYwX1D7VE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});